"""
This code tries to decrypt an output generated by encrypt() of encrypt_for_decrypt_2.py.

Find and fix the bug(s)!

Author: Omer Rosenbaum
"""
SECRET = "12,Vswiw$evi$vih0$Zmspixw$evi$fpyi0$Epp$q}$fewi0$Evi$fipsrk$xs$}sy"


def decrypt(encrypted):
    offset, encrypted_string = encrypted.split(',', 1)  # (offset, encrypted_string) = encrypted.split(',') --> offset, encrypted_string = encrypted.split(',')
    offset = (int(offset)-4)//2  # offset = int(offset)-4//2 --> offset = (int(offset)-4)//2
    for character in set(encrypted_string):
        encrypted_string = encrypted_string.replace(character, chr(ord(character)-offset))


    return encrypted_string

if __name__ == "__main__":
    print(decrypt(SECRET))